config/routes.rb
MobileAppManager::Engine.routes.draw do
  resources :mobileapps

end

app/models/mobile_app_manager/mobileapp.rb
module MobileAppManager
  class Mobileapp < ActiveRecord::Base
    attr_accessible :name, :version, :platform, :install_url, :relnotes_url
  end
end

app/controllers/mobile_app_manager/application_controller.rb
module MobileAppManager
  class ApplicationController < ActionController::Base
  end
end

app/controllers/mobile_app_manager/mobileapps_controller.rb
module MobileAppManager
  class MobileappsController < ApplicationController
    # GET /mobileapps
    # GET /mobileapps.json
    def index
      @mobileapps = Mobileapp.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @mobileapps }
      end
    end
  
    # GET /mobileapps/1
    # GET /mobileapps/1.json
    def show
      @mobileapp = Mobileapp.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @mobileapp }
      end
    end
  
    # GET /mobileapps/new
    # GET /mobileapps/new.json
    def new
      @mobileapp = Mobileapp.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @mobileapp }
      end
    end
  
    # GET /mobileapps/1/edit
    def edit
      @mobileapp = Mobileapp.find(params[:id])
    end
  
    # POST /mobileapps
    # POST /mobileapps.json
    def create
      @mobileapp = Mobileapp.new(params[:mobileapp])
  
      respond_to do |format|
        if @mobileapp.save
          format.html { redirect_to @mobileapp, notice: 'Mobileapp was successfully created.' }
          format.json { render json: @mobileapp, status: :created, location: @mobileapp }
        else
          format.html { render action: "new" }
          format.json { render json: @mobileapp.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /mobileapps/1
    # PUT /mobileapps/1.json
    def update
      @mobileapp = Mobileapp.find(params[:id])
  
      respond_to do |format|
        if @mobileapp.update_attributes(params[:mobileapp])
          format.html { redirect_to @mobileapp, notice: 'Mobileapp was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @mobileapp.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /mobileapps/1
    # DELETE /mobileapps/1.json
    def destroy
      @mobileapp = Mobileapp.find(params[:id])
      @mobileapp.destroy
  
      respond_to do |format|
        format.html { redirect_to mobileapps_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/mobile_app_manager/application_helper.rb
module MobileAppManager
  module ApplicationHelper
  end
end

app/helpers/mobile_app_manager/mobileapps_helper.rb
module MobileAppManager
  module MobileappsHelper
  end
end

app/views/layouts/mobile_app_manager/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobileAppManager</title>
  <%= stylesheet_link_tag    "mobile_app_manager/application", :media => "all" %>
  <%= javascript_include_tag "mobile_app_manager/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mobile_app_manager/mobileapps/_form.html.erb
<%= form_for(@mobileapp) do |f| %>
  <% if @mobileapp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mobileapp.errors.count, "error") %> prohibited this mobileapp from being saved:</h2>

      <ul>
      <% @mobileapp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :platform %><br />
    <%= f.text_field :platform %>
  </div>
  <div class="field">
    <%= f.label :install_url %><br />
    <%= f.text_field :install_url %>
  </div>
  <div class="field">
    <%= f.label :relnotes_url %><br />
    <%= f.text_field :relnotes_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mobile_app_manager/mobileapps/edit.html.erb
<h1>Editing mobileapp</h1>

<%= render 'form' %>

<%= link_to 'Show', @mobileapp %> |
<%= link_to 'Back', mobileapps_path %>

app/views/mobile_app_manager/mobileapps/index.html.erb
<h1>Listing mobileapps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Version</th>
    <th>Platform</th>
    <th>Install url</th>
    <th>Relnotes url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mobileapps.each do |mobileapp| %>
  <tr>
    <td><%= mobileapp.name %></td>
    <td><%= mobileapp.version %></td>
    <td><%= mobileapp.platform %></td>
    <td><%= mobileapp.install_url %></td>
    <td><%= mobileapp.relnotes_url %></td>
    <td><%= link_to 'Show', mobileapp %></td>
    <td><%= link_to 'Edit', edit_mobileapp_path(mobileapp) %></td>
    <td><%= link_to 'Destroy', mobileapp, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mobileapp', new_mobileapp_path %>

app/views/mobile_app_manager/mobileapps/new.html.erb
<h1>New mobileapp</h1>

<%= render 'form' %>

<%= link_to 'Back', mobileapps_path %>

app/views/mobile_app_manager/mobileapps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mobileapp.name %>
</p>

<p>
  <b>Version:</b>
  <%= @mobileapp.version %>
</p>

<p>
  <b>Platform:</b>
  <%= @mobileapp.platform %>
</p>

<p>
  <b>Install url:</b>
  <%= @mobileapp.install_url %>
</p>

<p>
  <b>Relnotes url:</b>
  <%= @mobileapp.relnotes_url %>
</p>


<%= link_to 'Edit', edit_mobileapp_path(@mobileapp) %> |
<%= link_to 'Back', mobileapps_path %>